[package]
name = "spl-type-length-value"
version = "0.6.0"
description = "Solana Program Library Type Length Value"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/hamkj7hpo/spl-type-length-value"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
spl-pod = { git = "https://github.com/hamkj7hpo/spl-pod.git", branch = "safe-pump-compat" }
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", branch = "safe-pump-compat" }
bytemuck = { version = "1.18.0", features = ["derive"] }

[workspace]
members = ["tlv-account-resolution"]

[patch.crates-io]
spl-tlv-account-resolution = { path = "./tlv-account-resolution" }
