[package]
name = "spl-type-length-value"
version = "0.6.0"
description = "Solana Program Library Type Length Value"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/hamkj7hpo/spl-type-length-value"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
spl-pod = { git = "https://github.com/hamkj7hpo/spl-pod.git", branch = "safe-pump-compat", package = "spl-pod" }
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", branch = "safe-pump-compat", package = "solana-program" }
spl-discriminator = { git = "https://github.com/hamkj7hpo/solana-program-library.git", rev = "f86fefd752bc4ca50adc8f06cd9ba579326c769e", package = "spl-discriminator" }
spl-program-error = { git = "https://github.com/hamkj7hpo/solana-program-library.git", rev = "f86fefd752bc4ca50adc8f06cd9ba579326c769e", package = "spl-program-error" }
bytemuck = { version = "1.18.0", features = ["derive"] }

[workspace]
members = ["tlv-account-resolution"]

[patch.crates-io]
spl-tlv-account-resolution = { path = "./tlv-account-resolution" }
